import path from "node:path";
import type { ClientRequest, IncomingMessage } from "node:http";

import react from "@vitejs/plugin-react";
import { defineConfig, loadEnv } from "vite";

import { mockApiPlugin } from "./src/mock-server/plugin";

const DEFAULT_GATEWAY_BASE_URL = "http://localhost:8001";
const DEFAULT_ONLYOFFICE_DEV_SERVER_URL = "http://localhost:8082";
const DEFAULT_OPENPENCIL_DEV_SERVER_URL = "http://localhost:3001";

type ProxyReqHook = {
  on: (
    event: "proxyReq",
    handler: (proxyReq: ClientRequest, req: IncomingMessage) => void,
  ) => void;
};

function getGatewayBaseURL(rawURL?: string): string {
  const url = rawURL ?? DEFAULT_GATEWAY_BASE_URL;
  return url.replace(/\/+$/, "");
}

function getOnlyOfficeDevServerURL(rawURL?: string): string {
  const url = rawURL ?? DEFAULT_ONLYOFFICE_DEV_SERVER_URL;
  return url.replace(/\/+$/, "");
}

function getOpenPencilDevServerURL(rawURL?: string): string {
  const url = rawURL ?? DEFAULT_OPENPENCIL_DEV_SERVER_URL;
  return url.replace(/\/+$/, "");
}

function getPortFromHost(host: string) {
  if (host.startsWith("[")) {
    return host.split("]:")[1] ?? "";
  }
  const parts = host.split(":");
  return parts.length > 1 ? parts.at(-1) ?? "" : "";
}

function applyBrowserForwardedHeaders(
  proxyReq: ClientRequest,
  req: IncomingMessage,
) {
  const host = req.headers.host?.trim();
  if (!host) {
    return;
  }

  // Public integration docs are generated by the gateway. Preserve the browser
  // origin through the Vite proxy so those docs do not leak compose-only hosts
  // such as `gateway:8001` into links users need to open.
  proxyReq.setHeader("X-Forwarded-Host", host);
  proxyReq.setHeader("X-Forwarded-Proto", "http");
  const port = getPortFromHost(host);
  if (port) {
    proxyReq.setHeader("X-Forwarded-Port", port);
  }
}

function createForwardedGatewayProxy(target: string) {
  return {
    target,
    changeOrigin: true,
    configure(proxy: ProxyReqHook) {
      proxy.on("proxyReq", applyBrowserForwardedHeaders);
    },
  };
}

function createGatewayProxy(
  target: string,
  onlyOfficeTarget: string,
  openPencilTarget: string,
) {
  return {
    // Keep the first-party `/v1/*` contract reachable from the app dev origin
    // so browser demos and docs pages can exercise the real gateway without
    // hardcoding a separate host in Docker dev.
    "/v1": createForwardedGatewayProxy(target),
    "/api": createForwardedGatewayProxy(target),
    "/open": createForwardedGatewayProxy(target),
    "/health": createForwardedGatewayProxy(target),
    "/sandbox-ide": {
      ...createForwardedGatewayProxy(target),
      ws: true,
    },
    // Keep local browser traffic aligned with production nginx by exposing
    // ONLYOFFICE under the same-origin `/onlyoffice` prefix during Vite dev.
    "/onlyoffice": {
      target: onlyOfficeTarget,
      changeOrigin: true,
      ws: true,
      rewrite: (path) => path.replace(/^\/onlyoffice/, ""),
    },
    // Keep OpenPencil under the same-origin `/openpencil` prefix so the
    // external design board can call back into `/api/design/*` without CORS.
    "/openpencil": {
      target: openPencilTarget,
      changeOrigin: true,
      ws: true,
      rewrite: (path) => path.replace(/^\/openpencil/, ""),
    },
  };
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, __dirname, "VITE_");
  // Prefer process env so the Docker dev stack can point the Vite proxy at
  // compose service DNS names without rewriting checked-in .env files.
  const gatewayBaseURL = getGatewayBaseURL(
    process.env.VITE_BACKEND_BASE_URL ?? env.VITE_BACKEND_BASE_URL,
  );
  const onlyOfficeDevServerURL = getOnlyOfficeDevServerURL(
    process.env.VITE_ONLYOFFICE_DEV_SERVER_URL ??
      env.VITE_ONLYOFFICE_DEV_SERVER_URL,
  );
  const openPencilDevServerURL = getOpenPencilDevServerURL(
    process.env.VITE_OPENPENCIL_DEV_SERVER_URL ??
      env.VITE_OPENPENCIL_DEV_SERVER_URL,
  );

  return {
    plugins: [react(), mockApiPlugin()],
    resolve: {
      alias: {
        "@": path.resolve(__dirname, "./src"),
      },
      dedupe: ["react", "react-dom"],
    },
    optimizeDeps: {
      include: [
        "react",
        "react-dom",
        "react-dom/client",
        "react-router-dom",
        "@radix-ui/react-tabs",
        "@radix-ui/react-dialog",
        "@radix-ui/react-dropdown-menu",
        "@radix-ui/react-tooltip",
        "@radix-ui/react-select",
        "@radix-ui/react-switch",
        "@radix-ui/react-scroll-area",
        "@radix-ui/react-collapsible",
        "@radix-ui/react-avatar",
        "@radix-ui/react-separator",
        "@radix-ui/react-slot",
        "@radix-ui/react-toggle",
        "@radix-ui/react-toggle-group",
        "@radix-ui/react-hover-card",
        "@radix-ui/react-progress",
      ],
    },
    server: {
      port: 3000,
      // `vite` 默认使用 development mode，这里按当前 mode 读取
      // `.env.development*` 里的网关地址，只用于开发时的反向代理。
      proxy: createGatewayProxy(
        gatewayBaseURL,
        onlyOfficeDevServerURL,
        openPencilDevServerURL,
      ),
    },
    build: {
      outDir: "dist",
    },
  };
});
